batch_size: 4
iters: 80000

train_dataset:
  type: ChangeDataset
  dataset_root: dataset/LEVIR-CD/
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: Normalize
      mean: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  mode: train

val_dataset:
  type: ChangeDataset
  dataset_root: dataset/LEVIR-CD/
  transforms:
    - type: Normalize
      mean: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: BCELoss
  coef: [1]

model:
  type: SegNet
  in_channels: 6
  num_classes: 2
